target-version = "py311"

[lint]
ignore = [
  "ANN101",
  "ANN102",
  "ANN401",
  "ARG002",
  "BLE001",
  "COM812",
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D107",
  "D407",
  "D413",
  "PLR0913",
  "RUF012",
]
select = ["ALL"]
