name: CI

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rye
        uses: eifinger/setup-rye@v1
      - name: Install Dependencies
        run: rye sync
      - name: Build Package
        run: |-
          source .venv/bin/activate
          rye build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  pre-release:
    name: Pre-release
    permissions:
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Create GitHub Release
        uses: liblaf/repo/.github/actions/release@main
        with:
          tag: dev
          files: dist/*
          pre-release: true
          recreate: true
